<a href="https://colab.research.google.com/github/mohith789p/Machine-Learning/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Perform arithmetic operations on NumPy arrays.

In [ ]:
# importing numpy module
import numpy as np

# creating array using numpy
a = np.array([1,2,3]) # array 01

# opertions on numpy array
print("Addition:", a+5) # adding 5 to array
print("Subration:", 5-a) # subtracting array from 5
print("Multiplication:", a*5) # multiplying 5 with array
print("Division:", 5/a) # dividing 5 with array

Addition: [6 7 8]
Subration: [4 3 2]
Multiplication: [ 5 10 15]
Division: [5.         2.5        1.66666667]


2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
# mean
mean = np.mean(a)
print(mean)

# standard deviation
sd = np.std(a)
print(sd)

2.0
0.816496580927726


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
# creating array
arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.

In [ ]:
rearr = np.reshape(arr,(2,4))
print(rearr)

[[10 15 20 25]
 [30 35 40 45]]


5. Given the array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`:  
• Extract the sub-matrix containing the last two rows and first two columns.  
• Replace all elements greater than 4 with 0.

In [ ]:
#  creating 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# extracting last two rows and first two columns
subArr = arr[1:,:2]
print(subArr)

# replacing all elements greater than 4 with 0
arr[arr>4] = 0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:  
• `a = np.array([1, 2, 3]) `  
• `b = np.array([4, 5, 6]) `  
• Perform element-wise addition, multiplication, and division.

In [ ]:
# creating array using numpy
a = np.array([1,2,3]) # array 01
b = np.array([4,5,6]) # array 02

# opertions on numpy array
print("Addition:", a+b) # addition of two numpy arrays
print("Subration:", b-a) # subtraction of two numpy arrays
print("Multiplication:", a*b) # multiplication of two numpy arrays
print("Division:", b/a) # division of two numpy arrays

Addition: [5 7 9]
Subration: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


7.  Create a random NumPy array of size (4, 4). Compute:  
• Mean of each column.  
• Maximum value of the entire array.  
• Sum of all elements.

In [ ]:
# creating random integer array
ramArr = np.random.rand(4,4)
print(ramArr)

# mean of each column
print(np.mean(ramArr, axis = 0))

# maximum value
print(np.max(ramArr))

# sum of all elements
print(np.sum(ramArr))

[[0.75731614 0.6363248  0.11391695 0.93357347]
 [0.39700005 0.5699474  0.57738231 0.2809202 ]
 [0.6543549  0.67387727 0.7008934  0.11799183]
 [0.40659773 0.43532319 0.24818284 0.33751711]]
[0.55381721 0.57886816 0.41009388 0.41750066]
0.9335734744431258
7.841119610392962


8. Given the array `arr = np.array([1, 2, 3, 4])`, add 10 to each element and multiply the result by 2.

In [ ]:
# creating array
arr = np.array([1,2,3,4])

# adding 10 to each elements
result = arr+10

# multiplying 2 to the result
result = result*2
print(result)

[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array `arr of shape (3, 4, 5)` with random integers ranging from 1 to 100.  
Perform the following:  
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.  
• Extract the first two rows and the last three columns from each "layer."  
• Replace all elements divisible by 3 with -1.  

In [ ]:
# Create a 3D NumPy array of shape (3, 4, 5) with random integers from 1 to 100
arr = np.random.randint(1, 101, size=(3, 4, 5))
print(arr)

# Extracting the second layer
layer = arr[1]
print(layer)

# Extracting the first two rows and the last three columns
subArr = arr[:, :2, -3:]
print(subArr)

# Replace all elements divisible by 3 with -1
result = np.where(arr % 3 == 0, -1, arr)
print(result)

[[[ 7 26 17  3 75]
  [81 37 88 66 92]
  [62 69 81 86 11]
  [41 77  4 57 51]]

 [[65 65 82 41 75]
  [14 87 19 12  5]
  [27 62  2 30 97]
  [99 96 51 52 81]]

 [[23 17 60 66 70]
  [29 38 31  6 47]
  [35 75 69 21 80]
  [46 60 40 67 55]]]
[[65 65 82 41 75]
 [14 87 19 12  5]
 [27 62  2 30 97]
 [99 96 51 52 81]]
[[[17  3 75]
  [88 66 92]]

 [[82 41 75]
  [19 12  5]]

 [[60 66 70]
  [31  6 47]]]
[[[ 7 26 17 -1 -1]
  [-1 37 88 -1 92]
  [62 -1 -1 86 11]
  [41 77  4 -1 -1]]

 [[65 65 82 41 -1]
  [14 -1 19 -1  5]
  [-1 62  2 -1 97]
  [-1 -1 -1 52 -1]]

 [[23 17 -1 -1 70]
  [29 38 31 -1 47]
  [35 -1 -1 -1 80]
  [46 -1 40 67 55]]]


10. Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20. Perform the following:   
• Subtract the mean of each row from its respective elements (row-wise normalization).  
• Create a new array by squaring all the elements in arr.  
• Find the indices of the top 3 maximum values in the entire array.  

In [ ]:
#  Creating a NumPy array arr of shape (3, 3) with random integers between 1 and 20.
arr = np.random.randint(1,20,(3,3))
print(arr)

# squaring the array
newArr = np.square(arr)
print(newArr)

# subtracting the mean of each row from its respective elements (row-wise normalization)
arr = arr - arr.mean(axis=1, keepdims=True)
print(arr)

# top 3 maximum values
sortArr = np.sort(arr.flatten())
print(sortArr[-3:])

[[14 16 14]
 [18  1 13]
 [13 15 12]]
[[196 256 196]
 [324   1 169]
 [169 225 144]]
[[-0.66666667  1.33333333 -0.66666667]
 [ 7.33333333 -9.66666667  2.33333333]
 [-0.33333333  1.66666667 -1.33333333]]
[1.66666667 2.33333333 7.33333333]
